### ISSUE TITLE
Define and use STX and ETX

### ISSUE THREAD

**Issue by c-bik** [K2InformaticsGmbH/ucp_parser#4]
Move from https://github.com/K2InformaticsGmbH/ucp_parser/blob/f1113dfd30f8af6be30b9f308743961cb79b0692/src/ucp_syntax.erl#L744-L745
to https://github.com/K2InformaticsGmbH/ucp_parser/blob/master/src/ucp_defines.hrl

**Comment by shamis** [comment]
fixed in #5
